export const GET_DATA_MOVIES = "movies/GET_DATA_MOVIES";
export const GET_DATA_MOVIES_DETAIL = "movies/GET_DATA_MOVIES_DETAIL";
export const GET_DATA_MOVIES_BYNAME = "movies/GET_DATA_MOVIES_BYNAME";
export const GET_DATA_MOVIES_LOADING = "movies/GET_DATA_MOVIES_LOADING";
export const GET_DATA_MOVIES_ERRORMESSAGE =
  "movies/GET_DATA_MOVIES_ERRORMESSAGE";
